<a href="https://colab.research.google.com/github/caffein1371/Carrier-Owl/blob/master/atma1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import polars as pl

In [3]:
!apt-get -y install fonts-ipafont

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
fonts-ipafont is already the newest version (00303-21ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 29 not upgraded.

In [4]:
!apt-get -y install fonts-ipafont-gothic

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
fonts-ipafont-gothic is already the newest version (00303-21ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 29 not upgraded.

In [5]:
!fc-list | grep "IPA"

/usr/share/fonts/opentype/ipafont-mincho/ipam.ttf: IPAMincho,IPA明朝:style=Regular
/usr/share/fonts/opentype/ipafont-gothic/ipagp.ttf: IPAPGothic,IPA Pゴシック:style=Regular
/usr/share/fonts/opentype/ipafont-mincho/ipamp.ttf: IPAPMincho,IPA P明朝:style=Regular
/usr/share/fonts/opentype/ipafont-gothic/ipag.ttf: IPAGothic,IPAゴシック:style=Regular
/usr/share/fonts/truetype/fonts-japanese-mincho.ttf: IPAMincho,IPA明朝:style=Regular
/usr/share/fonts/truetype/fonts-japanese-gothic.ttf: IPAGothic,IPAゴシック:style=Regular

In [6]:
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

# フォントのパスを指定
font_path = "/usr/share/fonts/opentype/ipafont-gothic/ipag.ttf"  # ここを適宜変更
font_prop = fm.FontProperties(fname=font_path)

# Matplotlib のデフォルトフォントを設定
plt.rcParams["font.family"] = font_prop.get_name()

print(f"使用フォント: {font_prop.get_name()}")  # どのフォントが設定されたか確認

使用フォント: IPAGothic

# EDA

In [7]:
#オンライン EC サイト上の購買ログデータです。オフライン購買データ (train_session.csv / train_log.csv 他) とユーザー ID や購入セッション ID で紐づかないことに注意してください。
ec_df = pd.read_csv('/content/drive/MyDrive/atma/ec_log.csv')
#商品を一意に特定することができるコード (jan code) に対して、その商品の属性を記載しているデータです。
jan_df = pd.read_csv('/content/drive/MyDrive/atma/jan.csv')
#提出データの情報
test_session_df = pd.read_csv('/content/drive/MyDrive/atma/test_session.csv')
#学習期間の完全なオフライン購買データ。どの購入セッションで何を何円で何個かったか、の情報が記入されています
train_log_df = pd.read_csv('/content/drive/MyDrive/atma/train_log.csv')
#学習・テスト期間の購入セッションのメタ情報。学習期間とテスト期間は日付で分割されています。 2024-10-31 までが学習期間、それ以降がテスト期間です。
train_session_df = pd.read_csv('/content/drive/MyDrive/atma/train_session.csv')

train_target_df = pd.read_csv('/content/drive/MyDrive/atma/train_target.csv')

<ipython-input-7-b106b868f3a2>:2: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  ec_df = pd.read_csv('/content/drive/MyDrive/atma/ec_log.csv')

In [8]:
target_col_list = ['チョコレート', 'ビール', 'ヘアケア', '米（5㎏以下）']

In [9]:
def remove_negative_purchase(train_session_df, train_log_df, jan_df):
    """
    下記を考慮して、返品されているsessionはややこしいのですべて除外する
    https://www.guruguru.science/competitions/26/discussions/1bc20930-cf84-43ed-93d0-c6ea64e504ee/
    """
    # 売上数量が0以下のデータを抽出（返品）
    neg_train_log_df = train_log_df[train_log_df["売上数量"] <= 0].copy()

    # 売上数量が正のデータのみ残す
    train_log_df = train_log_df[train_log_df["売上数量"] > 0].copy()

    # 返品された session を取得
    ignore_sessions = neg_train_log_df.merge(jan_df, on="JAN", how="inner")
    ignore_sessions = ignore_sessions[ignore_sessions["カテゴリ名"].isin(target_col_list)][["session_id"]]

    # `how="anti"` に相当する処理（除外する session_id を持つ行を削除）
    train_session_df = train_session_df.merge(ignore_sessions, on="session_id", how="left", indicator=True)
    train_session_df = train_session_df[train_session_df["_merge"] == "left_only"].drop(columns=["_merge"])

    return train_log_df, train_session_df

# 適用
train_log_df, train_session_df = remove_negative_purchase(
    train_session_df,
    train_log_df,
    jan_df,
)

In [10]:
from IPython.display import display
category_counts = jan_df["カテゴリ名"].value_counts()
print(category_counts.to_string())

カテゴリ名
トップス                6299
ボトムス                3486
ｾﾙﾌﾌﾞﾗﾝﾄﾞﾒｰｷｬｯﾌﾟ    2512
メンズトップス             2259
レディーストップス           2089
学用品                 1971
ヘアケア                1854
アウター                1722
筆記                  1653
レディースソックス           1579
単品メイク               1529
事務用品                1218
釣り具用品               1013
スキンケア               1001
女性頭髪                 992
メンズボトム               986
シーズン                 953
ヘアカラー                923
芳香消臭                 919
猫ウェット                918
メンズビューティ             913
ランジェリー＆ファンデーション      829
和洋菓子                 805
健康食品                 791
メンズソックス              747
菓子パン                 742
入浴剤                  721
芳香剤HC                715
メンズスポーツシューズ          714
エギ・ルアー               713
犬猫生活用品               673
ｶｳﾝｾﾘﾝｸﾞ化粧品          665
未登録等その他              637
珍味                   632
季節                   623
犬スナック                620
柔軟剤                  592
食器                   591
レディーススポーツシューズ        588
スナック                 588
小型PET                579
メンズルームウェア            574
漬物                   570
RTD                  565
ケースフィルム              559
チルド麺                 557
キッズインナー              551
水筒                   551
チョコレート               537
レディースボトム             525
洗顔                   524
ワークTシャツ              523
工具                   516
レディースルームウェア          513
紳士靴                  511
カップ麺                 511
植物・種                 499
医療衛生用品               492
手袋                   492
ゴルフ                  486
行楽                   485
ビール                  479
コーヒー・紅茶              476
ワイン                  476
婦人靴                  474
猫スナック                471
清酒                   463
子供                   461
焼肉                   456
充電器                  455
化粧小物                 435
香辛料                  435
バス用品                 432
焼酎                   426
練り                   426
男児ホビー                424
金封・封筒                417
猫ドライ                 415
カバー                  402
水槽用品                 398
葉茎菜類                 398
パンスト                 396
住居洗剤                 395
ガーデニング用品             388
アクセサリー(服飾)           384
洗車用品                 378
台所洗剤                 376
箸卓上                  375
生理用品                 365
紙巻たばこ                359
キャンディ                357
トレーニング               355
ビスクラ                 355
補修                   355
ジュニアシューズ             355
殺虫剤                  355
素材缶詰・瓶詰              344
カーアクセサリー             344
帽子                   343
調理小物                 340
フェイスマスク              336
皮膚薬                  335
犬ウェット                334
中華（調味料）              334
タオル                  334
風邪薬                  331
ボディソープ               330
清掃用品                 328
農産乾物                 325
弁当箱                  319
男児トレンド               317
一般玩具                 316
スパッツ                 301
唐揚げ                  297
BBQ                  297
ハブラシ                 297
ハミガキ                 296
つゆ                   294
要冷_洋生菓子              293
豆腐                   291
補修用品(カー用品)           289
ワークウェア               289
フレグランス               288
シリーズサプリ              288
衣料洗剤                 286
電球・管球・直管             285
OAパーツ                284
ワーキングシューズ            283
米菓                   283
バストイ                 280
服飾季節                 279
佃煮・煮豆・惣菜             277
犬ドライ                 275
インク                  273
小動物                  271
メンズサンダル              268
ベビーフード               267
大人オムツ                265
メンズバッグ               262
カーインテリア              262
ノベルティー               261
たれ                   253
おかず                  252
缶飲料                  252
取付金具                 251
カーテン                 250
雨具                   250
パスタ                  249
製菓材・デザート             246
保存容器                 244
レディースサンダル            244
ビジネストップス             243
ビギナースポーツ             241
食玩                   240
丼                    240
胃腸整腸                 237
レトルト                 234
健康飲料                 234
自転車パーツ               228
スピリッツ                228
ふりかけ・茶漬              227
果汁・野菜                226
レインウェア               225
豆菓子                  224
シーズンウェア              220
携帯パーツ（カー用品）          220
海産乾物                 220
洋酒                   219
作業小物                 216
エプロン・マット             214
加熱式たばこ               214
蒟蒻・ヘルシー              213
線香・ローソク              213
みそ                   212
果菜類                  212
ヨーグルト                212
フライパン                210
ドレッシング               210
グミ                   207
キッチン周り               207
レディースバッグ             205
ベビー用品                204
男性カミソリ               204
乾麺・半生麺・棒麺            200
袋麺                   197
しょうゆ                 196
オイル                  195
包丁・まな板               195
鍋・ケトル                194
ステーキ                 193
財布                   190
介護用品                 190
ゼリー                  190
カレールウ                188
茶                    188
スープ・春雨               188
冷凍                   187
ジャム・蜂蜜               186
ワイパー                 186
マスク                  186
大型PET                186
簡単調理                 184
チーズ                  183
石鹸・ハンド               180
水物フード                180
季節(洋菓子)              179
暖房                   178
メディア                 177
ドリンク剤                176
ＤＩＹ用品                173
トイレ用品                173
子供オムツ                170
マルモノ                 169
季節商品                 169
時計                   168
弁当                   166
トラベル                 166
防犯・補助照明              165
キッズソックス              164
コーヒー（日配飲料）           163
キッチンスポンジ             162
ゲーム                  162
りんご                  158
洗濯用品                 157
夏物                   157
雑玩具                  157
長靴                   156
炒め物                  155
グリル・ボンベ              154
ベルト                  153
おにぎり                 152
ガム                   152
配線                   151
土物類                  151
食卓パン                 150
即席みそ汁                148
海苔                   148
トマト                  148
女児トレンド               146
カー電装品                146
マリン用品                140
乳酸菌飲料                139
鍋                    139
ごはん・おかゆ・餅            139
焼菓子                  139
スクール                 138
インテリアグリーン            136
ショッピングバッグ            136
目薬                   135
その他セルフ化粧品            134
ソース                  134
麺                    133
衣服ケア                 132
おつまみ                 131
油                    130
アンパンマン               130
鳥                    129
外用消炎鎮痛剤              129
みかん                  127
ビタミン                 126
風味調味料                126
ラップ・ホイル              125
コーヒー・ケーキ             123
粉類                   123
イヤホン                 122
スリッパ                 122
保冷                   122
ビジネスボトムス             122
きのこ類                 122
煮込み                  121
ノンアルコール              119
ラグ                   119
ケーキ                  118
豆乳・植物性               118
携帯型サンドイッチ            118
酢                    118
マルチ                  117
お弁当用                 117
梨                    117
AV                   115
ぶどう                  115
水切・ポリ袋               113
食パン                  113
カイロ                  112
半生菓子                 111
ウインナー                110
ウエット・ポケットティッシュ       110
マウスウォッシュ             110
漢方                   110
電池                   110
季節(カー用品)             109
健康器具                 109
花                    107
梱包                   106
乾物                   106
メンズエステ               105
生食加工                 104
調理サラダ                104
トラベル・ソーイング           103
水・炭酸水                103
文具・玩具                103
クッション                103
揚げ                   102
軍足                   102
猫トイレタリー              102
収納用品(軽家具・収納)         102
和惣菜                  102
納豆                   101
チルド中華                 98
産直野菜                  98
犬トイレタリー               97
物干用品                  95
巻寿司                   95
消臭・除菌スプレー             95
ファニチャー                95
肥料                    94
米（5㎏以下）               94
炊事手袋                  94
煮物                    93
収納用品(サニタリー)           93
季節寝具                  93
女性カミソリ                91
巻物                    90
プレミアム                 90
女児ホビー                 89
釣りエサ                  89
解熱鎮痛剤                 88
シューケア用品               88
昆虫                    88
柿                     86
単品                    86
小袋                    85
散水                    85
生野菜サラダ                84
フライカツ                 83
フルーツ缶                 83
キッチン＆ハウスクリーン          82
挽肉                    82
喫煙・カメラ                81
根菜類                   80
家庭用ゴミ袋                79
薬味類                   79
バイク                   79
冷凍野菜                  78
盆・正月用品                78
スイミング                 77
グロサリーギフト              77
除草剤                   77
季節果物                  77
塩                     77
スキン                   76
キッズパジャマ               76
レディースエステ              75
砂糖                    75
ケチャップ                 75
調理家電その他               75
牛乳                    74
宿泊                    74
メロン                   73
ベビー（おもちゃ）             73
バッテリー・保安              73
漬物の素                  72
米飯                    72
シリアル                  72
着圧                    71
和洋即席                  71
シトラス                  71
ライト                   68
パスタ麺                  68
カットサラダ                68
組立家具                  67
衣類ケア                  67
デンタル用品                67
エステ                   66
ポン酢                   65
過去分                   65
季節(和菓子)               65
プリン                   65
柵（冷凍・養殖）              65
クリーナー                 64
プール用品                 64
夏物雑貨                  64
竿                     63
さつま芋                  61
米（2kg以下）              61
灯油・湯たんぽ               61
玉子                    60
調味料                   60
燃料                    60
不快                    60
簡便野菜                  58
とんかつ・ソテー              58
季節インテリア               57
布団                    57
焼き物                   55
前受金                   55
ハム                    55
ＦＦ・甘味                 55
枕                     55
中華                    55
日よけ                   55
生魚切身                  52
蒲焼・佃煮                 52
桃                     52
麺類                    52
軽食                    52
トイレットペーパー             51
刺身盛                   50
義歯用品                  49
布巾・簡易蛇口               48
水煮                    47
ワーク季節                 47
マヨネーズ                 47
造花・フェイク               46
シーリング・ペンダント           46
鮭鱒                    46
ピザ                    46
シーフード                 46
ディスプレイ                45
農産乾物(農産加工)            45
常温商品                  45
にぎり盛合せ                45
盛合せ                   44
コンタクト                 44
バター･マーガリン             44
惣菜パン                  43
ベーコン                  43
冷蔵庫・洗濯機               43
ビジネス羽織                43
海藻                    42
スイーツ                  42
天ぷら                   42
用土                    42
自転車本体                 40
干物                    40
園芸薬品                  40
防災防犯                  40
豆科野菜                  39
漬魚                    39
電気ポット・ケトル             38
キウイフルーツ               38
鎮静・鎮暈                 37
業務洗剤                  37
ふりかけ                  36
炊飯器                   36
シーズナブル                36
刺身（生）                 36
インテリアその他              35
ビジネスバッグ               35
浄水器                   35
魚卵                    35
刺身（冷凍・養殖）             35
レンジおかず                34
柵（生）                  34
プレート                  33
要冷_和生菓子               33
西瓜                    32
コットンパフ                32
玄関周り                  31
マットレス                 31
握り寿司                  31
運搬                    31
ご飯もの                  29
調理パン                  29
カットフルーツ               29
サラダチキン                29
生活家電雑貨                29
イベント                  28
シート・マット               28
漂白剤                   28
丼物                    27
BOXティッシュペーパー          27
バナナ                   26
みりん・料理酒               26
キッチンペーパー              26
殺虫・殺鼠                 26
犬猫インテリア用品             26
キッチン                  26
ジョイントマット              25
酢・甘酒                  25
調理家電雑貨（炭酸）            25
輸入果実                  24
ネクタイ                  24
ミール(鮮魚)               24
電子レンジ                 22
ミール(鮮魚塩干)             22
テーブル・チェア              22
いなり                   22
尽くし                   22
通年                    22
チルド米飯                 22
コロッケ                  21
かに                    21
小魚                    21
塩サバ                   20
IH・ガステーブル             20
産直果物                  20
飾り物                   20
フライ                   20
エビ                    19
鏡もち                   19
口臭ケア剤                 19
幼児                    19
オードブル(温)              17
凍魚切身                  17
トースター                 17
座椅子                   16
ホームグッズ                16
ハンガー・ラック              16
売上扱い                  15
もやし                   15
衣料・手芸用品               15
その他売上                 14
フォーマルグッズ              14
除雪用品                  14
洗剤ギフト                 14
米（10kg以上）             14
ちらし                   14
季節商材                  13
柑橘                    13
丸干し                   12
麦                     12
雑穀                    11
氷                     11
ホイップ                  11
アボカド                   9
原材料・包材                 9
吊下げ                    9
発芽野菜                   9
ベッド                    8
栄養補助                   8
いちご                    7
ギフト                    7
漬物(農産加工)               6
その他                    6
カスタマーその他               6
その他野菜類                 6
インテリア                  5
サニタリー                  5
原料・包材(農産加工)            5
もち米                    5
産直加工                   4
衛生用品                   4
コスメ＆ビューティ              4
ドライフルーツ                4
原料・包材(米飯)              3
食事パン                   3
バーガー、ドック               2
惣菜テナントその他              1
サンド                    1
鯨                      1
テーブルロール                1
果物加工                   1
ミート                    1

In [11]:
def create_session_feature(input_session_df: pd.DataFrame) -> pd.DataFrame:
    use_columns = [
        "時刻"
    ]

    return input_session_df[use_columns].copy()

In [12]:
create_session_feature(train_session_df)

         時刻
0         0
1         0
2         0
3         0
4         0
...      ..
2120866  23
2120867  23
2120868  23
2120869  23
2120870  23

[2119888 rows x 1 columns]

In [13]:
!pip install holidays

Requirement already satisfied: holidays in /usr/local/lib/python3.11/dist-packages (0.69)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.11/dist-packages (from holidays) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil->holidays) (1.17.0)

In [14]:
import holidays
from datetime import datetime

def create_date_feature(input_session_df):
    jp_holidays = holidays.Japan(years=datetime.now().year)
    date = pd.to_datetime(input_session_df["売上日"])

    output_df = pd.DataFrame()

    def is_holiday(date):
      return date in jp_holidays


    #output_df["年"] = date.dt.year
    output_df["曜日"] = date.dt.dayofweek
    output_df["日"] = date.dt.day
    output_df["祝日"] = date.apply(is_holiday)
    output_df['週末'] = output_df['曜日'].apply(lambda x: 1 if x in [5, 6] else 0)

    return output_df

In [15]:
create_date_feature(train_session_df)

         曜日   日     祝日  週末
0         0   1  False   0
1         0   1  False   0
2         0   1  False   0
3         0   1  False   0
4         0   1  False   0
...      ..  ..    ...  ..
2120866   3  31  False   0
2120867   3  31  False   0
2120868   3  31  False   0
2120869   3  31  False   0
2120870   3  31  False   0

[2119888 rows x 4 columns]

In [16]:
input_df = train_session_df.copy()

# 性別がとりうる値を最初に決める
categories = train_session_df["性別"].unique()

# 列にカテゴリを指定して, 性別の種類ごとに存在していたら 1 しないと 0 のデータに変換
pd.get_dummies(input_df["性別"], columns=categories)

            不明     女性     男性
0         True  False  False
1         True  False  False
2        False   True  False
3        False   True  False
4        False   True  False
...        ...    ...    ...
2120866  False  False   True
2120867  False  False   True
2120868  False  False   True
2120869  False  False   True
2120870   True  False  False

[2119888 rows x 3 columns]

In [17]:
def create_gender_feature(input_df):

    # 性別がとりうる値を最初に決める
    categories = train_session_df["性別"].unique()

    # 列にカテゴリを指定して, 性別の種類ごとに存在していたら 1 しないと 0 のデータに変換
    output_df = pd.get_dummies(input_df["性別"], columns=categories)

    return output_df

In [18]:
create_gender_feature(test_session_df)

           不明     女性     男性
0       False   True  False
1       False   True  False
2       False  False   True
3       False   True  False
4       False  False   True
...       ...    ...    ...
121410   True  False  False
121411  False   True  False
121412  False   True  False
121413  False   True  False
121414  False  False   True

[121415 rows x 3 columns]

In [19]:
def create_tenpo_feature(input_df):

    # 性別がとりうる値を最初に決める
    categories = train_session_df["店舗名"].unique()

    # 列にカテゴリを指定して, 性別の種類ごとに存在していたら 1 しないと 0 のデータに変換
    output_df = pd.get_dummies(input_df["店舗名"], columns=categories)

    return output_df

In [20]:
create_tenpo_feature(test_session_df)

          つくば    新宮店    日田店    益浦店    福岡空    門司店
0       False   True  False  False  False  False
1       False  False  False  False  False   True
2       False   True  False  False  False  False
3       False  False   True  False  False  False
4       False  False  False  False  False   True
...       ...    ...    ...    ...    ...    ...
121410  False   True  False  False  False  False
121411  False  False   True  False  False  False
121412  False  False   True  False  False  False
121413  False  False   True  False  False  False
121414  False  False  False  False  False   True

[121415 rows x 6 columns]

In [21]:
def create_nendai_feature(input_df):

    # 性別がとりうる値を最初に決める
    categories = train_session_df["年代"].unique()

    # 列にカテゴリを指定して, 性別の種類ごとに存在していたら 1 しないと 0 のデータに変換
    output_df = pd.get_dummies(input_df["年代"], columns=categories)

    return output_df

In [22]:
create_nendai_feature(test_session_df)

        10代以下    20代    30代    40代    50代    60代    70代  80代以上     不明
0       False  False  False   True  False  False  False  False  False
1       False  False  False  False  False  False  False   True  False
2       False  False  False  False  False  False   True  False  False
3       False  False  False  False  False   True  False  False  False
4       False  False  False  False  False   True  False  False  False
...       ...    ...    ...    ...    ...    ...    ...    ...    ...
121410  False  False  False   True  False  False  False  False  False
121411  False  False  False  False  False  False   True  False  False
121412  False  False  False  False   True  False  False  False  False
121413  False  False  False  False   True  False  False  False  False
121414  False  False  False  False  False   True  False  False  False

[121415 rows x 9 columns]

In [23]:
class CountFeature:
    def __init__(self, target_column: str):
        self.target_column = target_column

    def __call__(self, input_df):
        vc = train_session_df[self.target_column].value_counts()

        output_df = pd.DataFrame({
            self.target_column: input_df[self.target_column].map(vc)
        })

        return output_df.add_prefix("Count_")

In [24]:
def create_tenposu_feature(input_df):

    output_df = pd.DataFrame()
    # 列にカテゴリを指定して, 店舗数の種類ごとに存在していたら 1 しないと 0 のデータに変換
    output_df = CountFeature("店舗名")(test_session_df)

    return output_df

In [25]:
CountFeature("店舗名")(test_session_df)

        Count_店舗名
0          693866
1          293743
2          693866
3          189436
4          293743
...           ...
121410     693866
121411     189436
121412     189436
121413     189436
121414     293743

[121415 rows x 1 columns]

In [26]:
def create_kokyakucd_feature(input_df):

    output_df = pd.DataFrame()
    # 列にカテゴリを指定して, 顧客CDの種類ごとに存在していたら 1 しないと 0 のデータに変換
    output_df = CountFeature("顧客CD")(test_session_df)

    return output_df

In [27]:
#それぞれの顧客CDが何回そこに表れたかが出力される
CountFeature("顧客CD")(test_session_df)

        Count_顧客CD
0             20.0
1             33.0
2             18.0
3              NaN
4              6.0
...            ...
121410        33.0
121411         1.0
121412        15.0
121413         7.0
121414         NaN

[121415 rows x 1 columns]

In [28]:
TARGET_COLUMNS = ['チョコレート', 'ビール', 'ヘアケア', '米（5㎏以下）']

In [ ]:
# janコード → カテゴリ名に変換する辞書を作って
jan2category = jan_df.set_index("JAN")["カテゴリ名"]

# ログデータの jan コードをカテゴリに直す
category_names = train_log_df["JAN"].map(jan2category).rename("カテゴリ名")

# 予測対象のカテゴリが入っているとリークになる可能性があるので除外
idx_rm = category_names.isin(TARGET_COLUMNS)
category_names = category_names[~idx_rm].reset_index(drop=True)

In [ ]:
#session_idから顧客CDの辞書を作る
session2customer = train_session_df.set_index("session_id")["顧客CD"]
#renameしてindexを付け直す．リークしないように
_customers = train_log_df["session_id"].map(session2customer).rename("顧客CD")[~idx_rm].reset_index(drop=True)

In [ ]:
customer_category_total_count_df = train_log_df[~idx_rm]\
    .groupby([_customers, category_names])["売上数量"]\
    .sum().unstack()

customer_category_total_count_df = customer_category_total_count_df.fillna(0).astype(int)

In [ ]:
from sklearn.decomposition import TruncatedSVD

In [ ]:
clf = TruncatedSVD(n_components=30)
z = clf.fit_transform(customer_category_total_count_df.values)
svd_customer_df = pd.DataFrame(z, index=customer_category_total_count_df.index)
svd_customer_df.head()

In [ ]:
def create_customer_purchase_feature(input_df):
    """この実装では svd で圧縮した購買履歴データがある前提で記述をしています"""

    output_df = pd.merge(input_df["顧客CD"], svd_customer_df, on="顧客CD", how="left").drop(columns=["顧客CD"])
    return output_df.add_prefix("customer_purchase_")

In [ ]:
train_log_df = pl.from_pandas(train_log_df)
jan_df = pl.from_pandas(jan_df)
train_session_df = pl.from_pandas(train_session_df)

In [ ]:
def create_category_matrix(
    train_log_df,
    jan_df,
):
  """
  縦軸session_id, 横軸カテゴリ名のmatrixを作る
  """
  category_df = train_log_df.join(
        jan_df, on="JAN", how="left"
  ).group_by(["session_id", "カテゴリ名"]).agg(
      pl.col("売上数量").sum().alias("売上数量")
  )

  category_matrix_df = category_df.pivot(
      values="売上数量",
      index="session_id",
      columns="カテゴリ名",
      aggregate_function="sum"
  )

  # 売上数量を0, 1に収める

  category_matrix_df = category_matrix_df.with_columns([
      pl.col(col).clip(0,1)
      for col in category_matrix_df.columns if col != "session_id"
  ]).fill_null(0)

  return category_matrix_df

purchase_ratio_df = pl.concat(
    [
        train_session_df[["session_id", "店舗名", "年代", "性別", "顧客CD"]],
        create_category_matrix(train_log_df, jan_df)[Ctarget_col_list]
    ], how="horizontal"
)

# purchase_ratio_df の作成
purchase_ratio_df = pd.concat(
    [
        train_session_df[["session_id", "店舗名", "年代", "性別", "顧客CD"]],
        create_category_matrix(train_log_df, jan_df)[target_col_list]
    ], axis=1
)

In [ ]:
def purchase_ratio_feature(input_session_df, purchase_ratio_df):
    # `session_id` で結合
    merged_df = input_session_df.merge(purchase_ratio_df, on="session_id", how="left")

    # 顧客CDごとの購入比率
    customer_purchase_ratio_df = merged_df.groupby("顧客CD")[CFG.target_col_list].mean()
    customer_purchase_ratio_df = customer_purchase_ratio_df.add_prefix("顧客CD_purchase_ratio_").reset_index()

    # 性別ごとの購入比率
    sex_purchase_ratio_df = merged_df.groupby("性別")[CFG.target_col_list].mean()
    sex_purchase_ratio_df = sex_purchase_ratio_df.add_prefix("性別_purchase_ratio_").reset_index()

    # 年代ごとの購入比率
    age_purchase_ratio_df = merged_df.groupby("年代")[CFG.target_col_list].mean()
    age_purchase_ratio_df = age_purchase_ratio_df.add_prefix("年代_purchase_ratio_").reset_index()

    # 店舗名ごとの購入比率
    shop_purchase_ratio_df = merged_df.groupby("店舗名")[CFG.target_col_list].mean()
    shop_purchase_ratio_df = shop_purchase_ratio_df.add_prefix("店舗名_purchase_ratio_").reset_index()

    return customer_purchase_ratio_df, sex_purchase_ratio_df, age_purchase_ratio_df, shop_purchase_ratio_df

In [ ]:
customer_purchase_ratio_df, sex_purchase_ratio_df, age_purchase_ratio_df, shop_purchase_ratio_df = purchase_ratio_feature(train_input_session_df, purchase_ratio_df)

In [49]:
from typing import List
from contextlib import contextmanager
from time import time

# コードの実行時間を計測する便利関数
# https://github.com/nyk510/vivid/blob/master/vivid/utils.py
class Timer:
    def __init__(self, logger=None, format_str="{:.3f}[s]", prefix=None, suffix=None, sep=" "):

        if prefix: format_str = str(prefix) + sep + format_str
        if suffix: format_str = format_str + sep + str(suffix)
        self.format_str = format_str
        self.logger = logger
        self.start = None
        self.end = None

    @property
    def duration(self):
        if self.end is None:
            return 0
        return self.end - self.start

    def __enter__(self):
        self.start = time()

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.end = time()
        out_str = self.format_str.format(self.duration)
        if self.logger:
            self.logger.info(out_str)
        else:
            print(out_str)

def build_feature(input_df: pd.DataFrame, feature_functions: List) -> pd.DataFrame:
    # 出力するデータフレームを空で用意して
    out_df = pd.DataFrame()

    print("start build features...")

    # 各特徴生成関数ごとで
    for func in feature_functions:

        with Timer(prefix=f"create {func.__name__}"):
            # 特徴量を作成し
            _df = func(input_df)

        # 横方向 (axis=1) にがっちゃんこ (concat) する
        out_df = pd.concat([out_df, _df], axis=1)

    return out_df

In [64]:
functions = [
    create_session_feature,
    create_gender_feature,
    create_date_feature,
    create_tenpo_feature,
    create_nendai_feature,
    create_tenposu_feature,
    create_kokyakucd_feature,
    create_customer_purchase_feature,
]

In [65]:
with Timer(prefix="build train..."):
    train_feat_df = build_feature(train_session_df, feature_functions=functions)

with Timer(prefix="build test..."):
    test_feat_df = build_feature(test_session_df, feature_functions=functions)

start build features...
create create_session_feature 0.020[s]
create create_gender_feature 0.328[s]
create create_date_feature 7.234[s]
create create_tenpo_feature 0.256[s]
create create_nendai_feature 0.237[s]
create create_tenposu_feature 0.175[s]
create create_kokyakucd_feature 1.348[s]
create create_customer_purchase_feature 3.284[s]
build train... 13.448[s]
start build features...
create create_session_feature 0.003[s]
create create_gender_feature 0.183[s]
create create_date_feature 0.372[s]
create create_tenpo_feature 0.111[s]
create create_nendai_feature 0.104[s]
create create_tenposu_feature 0.178[s]
create create_kokyakucd_feature 1.332[s]
create create_customer_purchase_feature 0.251[s]
build test... 2.560[s]

In [66]:
feat = pd.read_csv('/content/drive/MyDrive/atma/feature_train_2.csv')

In [67]:
feat_test = pd.read_csv('/content/drive/MyDrive/atma/feature_test_2.csv')

In [68]:
feat

         choco_feature  bear_feature  haircare_feature  rice_feature
0             1.286275      1.020426          1.202358      0.924809
1             1.286275      1.020426          1.202358      0.924809
2             1.286275      0.985439          0.852432      0.752939
3             1.286275      0.985439          0.852432      0.752939
4             1.286275      0.985439          0.852432      0.752939
...                ...           ...               ...           ...
2120546       1.554015      1.897273          1.614320      1.983749
2120547       1.554015      1.897273          1.614320      1.983749
2120548       1.554015      1.897273          1.614320      1.983749
2120549       1.554015      1.897273          1.614320      1.983749
2120550       1.374665      1.018835          1.058467      1.028726

[2120551 rows x 4 columns]

In [69]:
train_feat_df = pd.concat([train_feat_df, feat], axis=1)

In [70]:
train_feat_df

,時刻,不明,女性,男性,曜日,日,祝日,つくば,新宮店,日田店,...,customer_purchase_24,customer_purchase_25,customer_purchase_26,customer_purchase_27,customer_purchase_28,customer_purchase_29,choco_feature,bear_feature,haircare_feature,rice_feature
0,0,True,False,False,0,1,False,True,False,False,...,-1.836609,0.056516,-1.003705,1.197711,0.330107,-0.177918,1.286275,1.020426,1.202358,0.924809
1,0,True,False,False,0,1,False,True,False,False,...,1.682822,-0.546055,-4.539963,-0.526346,1.292873,0.751415,1.286275,1.020426,1.202358,0.924809
2,0,False,True,False,0,1,False,True,False,False,...,1.830641,6.269339,-2.047747,6.720994,2.081028,-3.806281,1.286275,0.985439,0.852432,0.752939
3,0,False,True,False,0,1,False,True,False,False,...,1.528740,0.628689,0.445982,-1.265130,-0.436215,-2.413832,1.286275,0.985439,0.852432,0.752939
4,0,False,True,False,0,1,False,True,False,False,...,-7.773605,1.821006,-2.009421,-6.437783,-1.534269,9.068636,1.286275,0.985439,0.852432,0.752939
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2120546,23,False,False,True,3,31,False,False,False,False,...,-0.021917,0.075598,-0.007400,-0.000587,0.094081,0.016387,1.554015,1.897273,1.614320,1.983749
2120547,23,False,False,True,3,31,False,False,False,False,...,-0.250057,-0.214091,0.316939,-0.314654,-0.031169,-0.168987,1.554015,1.897273,1.614320,1.983749
2120548,23,False,False,True,3,31,False,False,False,False,...,-0.003753,0.002975,-0.013249,0.006543,0.009306,0.010949,1.554015,1.897273,1.614320,1.983749
2120549,23,False,False,True,3,31,False,False,False,False,...,-4.296553,6.642505,2.369098,-9.055719,2.809552,-21.865950,1.554015,1.897273,1.614320,1.983749
2120550,23,True,False,False,3,31,False,False,False,False,...,-0.370319,-0.124995,0.157733,0.445332,-0.058550,-0.133500,1.374665,1.018835,1.058467,1.028726

In [71]:
test_feat_df = pd.concat([test_feat_df, feat_test], axis=1)

In [72]:
assert train_feat_df.columns.equals(test_feat_df.columns)

In [73]:
test_feat_df.head()

,時刻,不明,女性,男性,曜日,日,祝日,つくば,新宮店,日田店,...,customer_purchase_24,customer_purchase_25,customer_purchase_26,customer_purchase_27,customer_purchase_28,customer_purchase_29,choco_feature,bear_feature,haircare_feature,rice_feature
0,17,False,True,False,6,3,True,False,True,False,...,0.098578,6.085979,-2.153290,-6.624559,-0.321624,-9.945392,1.600709,0.808032,0.808032,0.964582
1,17,False,True,False,4,1,False,False,False,False,...,-3.347201,0.443796,-1.701189,-0.060082,0.702007,1.515831,1.242665,1.035536,1.035536,4.740614
2,11,False,False,True,3,7,False,False,True,False,...,-4.053895,-5.444377,0.250034,-1.641328,1.423383,-2.210929,1.258484,1.988388,1.988388,4.834450
3,8,False,True,False,4,22,False,False,False,True,...,NaN,NaN,NaN,NaN,NaN,NaN,1.407995,1.628637,1.628637,3.221336
4,15,False,False,True,5,9,False,False,False,False,...,-1.382703,0.444577,0.523266,-1.120246,-0.665612,-0.993565,2.485013,1.654474,1.654474,1.315418

# 正解ラベル

In [74]:
TARGET_COLUMNS = ['チョコレート', 'ビール', 'ヘアケア', '米（5㎏以下）']

In [75]:
# def create_target_data(train_session_df, log_df):
#     output_df = pd.DataFrame()
#     for c in TARGET_COLUMNS:
#         print(f"\t- start {c}")
#         idx = jan_df["カテゴリ名"] == c
#         target_jan = jan_df["JAN"][idx].values
#         is_target = log_df["JAN"].isin(target_jan)

#         # セッションごとに, 対象商品のレコードの売上個数を合計して
#         total_amount_by_session = log_df[is_target].groupby("session_id")["売上数量"].sum()

#         # 1 個以上購入があったセッションを positive (購入あり) セッションとみなし
#         positive_sessions = total_amount_by_session[total_amount_by_session > 0].index

#         # 学習用データのセッションと比較・含まれているとき 1 そうでないとき 0 になるようにする
#         y_true = train_session_df["session_id"].isin(positive_sessions).astype(int)

#         output_df[c] = y_true

#     return output_df

In [76]:
def create_target_data(train_session_df, log_df, jan_df, threshold=1, price_threshold=None):
    output_df = pd.DataFrame()

    # 負の売上数量を削除（返品を除外）
    log_df = log_df[log_df["売上数量"] >= 0]

    for c in TARGET_COLUMNS:
        print(f"\t- start {c}")
        idx = jan_df["カテゴリ名"] == c
        target_jan = jan_df["JAN"][idx].values
        is_target = log_df["JAN"].isin(target_jan)

        # セッションごとの売上個数合計
        total_amount_by_session = log_df[is_target].groupby("session_id")["売上数量"].sum()

        # 売上金額のしきい値がある場合は、金額ベースのフィルタ
        if price_threshold is not None:
            total_sales_by_session = log_df[is_target].groupby("session_id")["売上金額"].sum()
            positive_sessions = total_sales_by_session[total_sales_by_session >= price_threshold].index
        else:
            positive_sessions = total_amount_by_session[total_amount_by_session >= threshold].index

        # 学習用データのセッションと比較
        y_true = train_session_df["session_id"].isin(positive_sessions).astype(int)

        output_df[c] = y_true

    return output_df

In [77]:
with Timer(prefix="create target..."):
    target_df = create_target_data(train_session_df=train_session_df, log_df=train_log_df,jan_df=jan_df)

	- start チョコレート
	- start ビール
	- start ヘアケア
	- start 米（5㎏以下）
create target... 7.919[s]

In [78]:
target_df.mean()

チョコレート     0.068832
ビール        0.074139
ヘアケア       0.028059
米（5㎏以下）    0.019925
dtype: float64

In [105]:
train_target_df.mean()

チョコレート     0.068940
ビール        0.074257
ヘアケア       0.028136
米（5㎏以下）    0.019964
dtype: float64

In [79]:
from sklearn.model_selection import KFold

fold = KFold(n_splits=5, shuffle=True, random_state=510)
cv = list(fold.split(train_feat_df.values, train_target_df.iloc[:, 0].values))

In [80]:
from sklearn.metrics import roc_auc_score
import lightgbm as lgbm

def fit_lgbm(X,
             y,
             cv,
             params: dict=None,
             verbose: int=50):
    """lightGBM を CrossValidation の枠組みで学習を行なう function"""

    # パラメータがないときは、空の dict で置き換える
    if params is None:
        params = {}

    models = []
    n_records = len(X)
    # training data の target と同じだけのゼロ配列を用意
    oof_pred = np.zeros((n_records, ), dtype=np.float32)

    for i, (idx_train, idx_valid) in enumerate(cv):
        # この部分が交差検証のところです。データセットを cv instance によって分割します
        # training data を trian/valid に分割
        x_train, y_train = X[idx_train], y[idx_train]
        x_valid, y_valid = X[idx_valid], y[idx_valid]

        clf = lgbm.LGBMClassifier(**params)

        with Timer(prefix="fit fold={} ".format(i)):
            clf.fit(x_train, y_train,
                    eval_set=[(x_valid, y_valid)],
                    callbacks=[lgbm.callback.early_stopping(stopping_rounds=100),
                      lgbm.log_evaluation(period=verbose),],)

        # 予測確率を出力してもらう
        pred_i = clf.predict_proba(x_valid)
        # output の形は shape = (n_samples, 2) になっていることに注意!
        y_pred_prob = pred_i[:, 1]

        oof_pred[idx_valid] = y_pred_prob
        models.append(clf)

        # 今回の指標の MAE で計算する
        score = roc_auc_score(y_valid, y_pred_prob, )
        print(f" - fold{i} - {score:.4f}")

    return oof_pred, models

In [81]:
params = {
    # 目的関数. これの意味で最小となるようなパラメータを探します.
    # 今回は 0-1 問題なので, よく使われる binary を利用します
    "objective": "binary",

     # 学習率. 小さいほどなめらかな決定境界が作られて性能向上に繋がる場合が多いです、
    # がそれだけ木を作るため学習に時間がかかります
    "learning_rate": .1,

    # 木の最大数. early_stopping という枠組みで木の数は制御されるようにしていますのでとても大きい値を指定しておきます.
    "n_estimators": 10000,

    # 特徴重要度計算のロジック(後述)
    "importance_type": "gain",
    "random_state": 510,

    # ログがあまりに多いので少なめに.
    "verbose": -1
}
#futre work hypper parameter

In [ ]:
# 今回は予測対象が複数あるので for 文を使ってそれぞれの列に対して予測をしてくれるモデルを作ります.
results = []

for col_i in TARGET_COLUMNS:
    with Timer(prefix=f"column={col_i}"):
        oof, models = fit_lgbm(X=train_feat_df.values, y=target_df[col_i].values, cv=cv, params=params)

    results.append([oof, models])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

Training until validation scores don't improve for 100 rounds
[50]	valid_0's binary_logloss: 0.231267
[100]	valid_0's binary_logloss: 0.228179
[150]	valid_0's binary_logloss: 0.226131
[200]	valid_0's binary_logloss: 0.224671
[250]	valid_0's binary_logloss: 0.223545
[300]	valid_0's binary_logloss: 0.22257
[350]	valid_0's binary_logloss: 0.221797
[400]	valid_0's binary_logloss: 0.221202
[450]	valid_0's binary_logloss: 0.220606
[500]	valid_0's binary_logloss: 0.22011
[550]	valid_0's binary_logloss: 0.219687
[600]	valid_0's binary_logloss: 0.21932
[650]	valid_0's binary_logloss: 0.218928
[700]	valid_0's binary_logloss: 0.218596
[750]	valid_0's binary_logloss: 0.218213
[800]	valid_0's binary_logloss: 0.217906
[850]	valid_0's binary_logloss: 0.217619
[900]	valid_0's binary_logloss: 0.217374
[950]	valid_0's binary_logloss: 0.217115
[1000]	valid_0's binary_logloss: 0.216968
[1050]	valid_0's binary_logloss: 0.216773
[1100]	valid_0's binary_logloss: 0.216609
[1150]	valid_0's binary_logloss: 0.216445
[1200]	valid_0's binary_logloss: 0.216291
[1250]	valid_0's binary_logloss: 0.21617
[1300]	valid_0's binary_logloss: 0.216003
[1350]	valid_0's binary_logloss: 0.215889
[1400]	valid_0's binary_logloss: 0.215807
[1450]	valid_0's binary_logloss: 0.215704
[1500]	valid_0's binary_logloss: 0.215562
[1550]	valid_0's binary_logloss: 0.215449
[1600]	valid_0's binary_logloss: 0.215404
[1650]	valid_0's binary_logloss: 0.215307
[1700]	valid_0's binary_logloss: 0.215235
[1750]	valid_0's binary_logloss: 0.215135
[1800]	valid_0's binary_logloss: 0.215044
[1850]	valid_0's binary_logloss: 0.215021
[1900]	valid_0's binary_logloss: 0.214945
[1950]	valid_0's binary_logloss: 0.214871
[2000]	valid_0's binary_logloss: 0.214804
[2050]	valid_0's binary_logloss: 0.21478
[2100]	valid_0's binary_logloss: 0.214801
Early stopping, best iteration is:
[2018]	valid_0's binary_logloss: 0.214772
fit fold=0  630.540[s]

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

 - fold0 - 0.7736

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

Training until validation scores don't improve for 100 rounds
[50]	valid_0's binary_logloss: 0.234977
[100]	valid_0's binary_logloss: 0.231622
[150]	valid_0's binary_logloss: 0.229671
[200]	valid_0's binary_logloss: 0.228269
[250]	valid_0's binary_logloss: 0.227133
[300]	valid_0's binary_logloss: 0.226224
[350]	valid_0's binary_logloss: 0.225426
[400]	valid_0's binary_logloss: 0.224795
[450]	valid_0's binary_logloss: 0.22423
[500]	valid_0's binary_logloss: 0.223634
[550]	valid_0's binary_logloss: 0.223124
[600]	valid_0's binary_logloss: 0.222653
[650]	valid_0's binary_logloss: 0.222314
[700]	valid_0's binary_logloss: 0.221938
[750]	valid_0's binary_logloss: 0.221629
[800]	valid_0's binary_logloss: 0.221364
[850]	valid_0's binary_logloss: 0.221119
[900]	valid_0's binary_logloss: 0.220964
[950]	valid_0's binary_logloss: 0.220781
[1000]	valid_0's binary_logloss: 0.220561
[1050]	valid_0's binary_logloss: 0.220373
[1100]	valid_0's binary_logloss: 0.22022
[1150]	valid_0's binary_logloss: 0.220057
[1200]	valid_0's binary_logloss: 0.219932
[1250]	valid_0's binary_logloss: 0.219828
[1300]	valid_0's binary_logloss: 0.219744
[1350]	valid_0's binary_logloss: 0.219567
[1400]	valid_0's binary_logloss: 0.219455
[1450]	valid_0's binary_logloss: 0.219349
[1500]	valid_0's binary_logloss: 0.219259
[1550]	valid_0's binary_logloss: 0.219186
[1600]	valid_0's binary_logloss: 0.219088
[1650]	valid_0's binary_logloss: 0.219001
[1700]	valid_0's binary_logloss: 0.218925
[1750]	valid_0's binary_logloss: 0.218805
[1800]	valid_0's binary_logloss: 0.218739
[1850]	valid_0's binary_logloss: 0.218661
[1900]	valid_0's binary_logloss: 0.218633
[1950]	valid_0's binary_logloss: 0.218556
[2000]	valid_0's binary_logloss: 0.2185
[2050]	valid_0's binary_logloss: 0.218467
[2100]	valid_0's binary_logloss: 0.218472
[2150]	valid_0's binary_logloss: 0.218435
[2200]	valid_0's binary_logloss: 0.218412
[2250]	valid_0's binary_logloss: 0.218361
[2300]	valid_0's binary_logloss: 0.218297
[2350]	valid_0's binary_logloss: 0.218279
[2400]	valid_0's binary_logloss: 0.218235
[2450]	valid_0's binary_logloss: 0.218202
[2500]	valid_0's binary_logloss: 0.218192
[2550]	valid_0's binary_logloss: 0.218173
[2600]	valid_0's binary_logloss: 0.218152
[2650]	valid_0's binary_logloss: 0.21814
[2700]	valid_0's binary_logloss: 0.218142
[2750]	valid_0's binary_logloss: 0.2181
[2800]	valid_0's binary_logloss: 0.218108
[2850]	valid_0's binary_logloss: 0.218086
[2900]	valid_0's binary_logloss: 0.218075
[2950]	valid_0's binary_logloss: 0.218088
[3000]	valid_0's binary_logloss: 0.218103
Early stopping, best iteration is:
[2923]	valid_0's binary_logloss: 0.218062
fit fold=1  851.728[s]

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

 - fold1 - 0.7722

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

Training until validation scores don't improve for 100 rounds
[50]	valid_0's binary_logloss: 0.233332
[100]	valid_0's binary_logloss: 0.229913
[150]	valid_0's binary_logloss: 0.227873
[200]	valid_0's binary_logloss: 0.226429
[250]	valid_0's binary_logloss: 0.225379
[300]	valid_0's binary_logloss: 0.224614
[350]	valid_0's binary_logloss: 0.223737
[400]	valid_0's binary_logloss: 0.223124
[450]	valid_0's binary_logloss: 0.222501
[500]	valid_0's binary_logloss: 0.221975
[550]	valid_0's binary_logloss: 0.221472
[600]	valid_0's binary_logloss: 0.221045
[650]	valid_0's binary_logloss: 0.220671
[700]	valid_0's binary_logloss: 0.22029
[750]	valid_0's binary_logloss: 0.219989
[800]	valid_0's binary_logloss: 0.219673
[850]	valid_0's binary_logloss: 0.219501
[900]	valid_0's binary_logloss: 0.219268
[950]	valid_0's binary_logloss: 0.218965
[1000]	valid_0's binary_logloss: 0.218755
[1050]	valid_0's binary_logloss: 0.218596
[1100]	valid_0's binary_logloss: 0.218486
[1150]	valid_0's binary_logloss: 0.218327
[1200]	valid_0's binary_logloss: 0.218199
[1250]	valid_0's binary_logloss: 0.218113
[1300]	valid_0's binary_logloss: 0.218014
[1350]	valid_0's binary_logloss: 0.217893
[1400]	valid_0's binary_logloss: 0.217798
[1450]	valid_0's binary_logloss: 0.217705
[1500]	valid_0's binary_logloss: 0.217666
[1550]	valid_0's binary_logloss: 0.217527
[1600]	valid_0's binary_logloss: 0.217436
[1650]	valid_0's binary_logloss: 0.217333
[1700]	valid_0's binary_logloss: 0.217212
[1750]	valid_0's binary_logloss: 0.217157
[1800]	valid_0's binary_logloss: 0.217059
[1850]	valid_0's binary_logloss: 0.217006
[1900]	valid_0's binary_logloss: 0.216962
[1950]	valid_0's binary_logloss: 0.216926
[2000]	valid_0's binary_logloss: 0.216874
[2050]	valid_0's binary_logloss: 0.216828
[2100]	valid_0's binary_logloss: 0.216778
[2150]	valid_0's binary_logloss: 0.216745
[2200]	valid_0's binary_logloss: 0.216706
[2250]	valid_0's binary_logloss: 0.21664
[2300]	valid_0's binary_logloss: 0.216605
[2350]	valid_0's binary_logloss: 0.216527
[2400]	valid_0's binary_logloss: 0.216489
[2450]	valid_0's binary_logloss: 0.216466
[2500]	valid_0's binary_logloss: 0.216496
Early stopping, best iteration is:
[2440]	valid_0's binary_logloss: 0.21646
fit fold=2  729.616[s]

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

 - fold2 - 0.7734

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

Training until validation scores don't improve for 100 rounds
[50]	valid_0's binary_logloss: 0.231565
[100]	valid_0's binary_logloss: 0.228073
[150]	valid_0's binary_logloss: 0.226049
[200]	valid_0's binary_logloss: 0.22456
[250]	valid_0's binary_logloss: 0.223467
[300]	valid_0's binary_logloss: 0.22266
[350]	valid_0's binary_logloss: 0.221933
[400]	valid_0's binary_logloss: 0.221328
[450]	valid_0's binary_logloss: 0.220706
[500]	valid_0's binary_logloss: 0.220118
[550]	valid_0's binary_logloss: 0.219625
[600]	valid_0's binary_logloss: 0.219199
[650]	valid_0's binary_logloss: 0.218741
[700]	valid_0's binary_logloss: 0.218422
[750]	valid_0's binary_logloss: 0.218085
[800]	valid_0's binary_logloss: 0.217857
[850]	valid_0's binary_logloss: 0.217646
[900]	valid_0's binary_logloss: 0.217415
[950]	valid_0's binary_logloss: 0.21716
[1000]	valid_0's binary_logloss: 0.217017
[1050]	valid_0's binary_logloss: 0.216821
[1100]	valid_0's binary_logloss: 0.216675
[1150]	valid_0's binary_logloss: 0.216447
[1200]	valid_0's binary_logloss: 0.216323
[1250]	valid_0's binary_logloss: 0.216182
[1300]	valid_0's binary_logloss: 0.215993
[1350]	valid_0's binary_logloss: 0.21587
[1400]	valid_0's binary_logloss: 0.215752
[1450]	valid_0's binary_logloss: 0.215664
[1500]	valid_0's binary_logloss: 0.215574
[1550]	valid_0's binary_logloss: 0.215465
[1600]	valid_0's binary_logloss: 0.215358
[1650]	valid_0's binary_logloss: 0.215304
[1700]	valid_0's binary_logloss: 0.215231
[1750]	valid_0's binary_logloss: 0.215142
[1800]	valid_0's binary_logloss: 0.21505
[1850]	valid_0's binary_logloss: 0.214991
[1900]	valid_0's binary_logloss: 0.21497
[1950]	valid_0's binary_logloss: 0.214921
[2000]	valid_0's binary_logloss: 0.214856
[2050]	valid_0's binary_logloss: 0.214788
[2100]	valid_0's binary_logloss: 0.214775
[2150]	valid_0's binary_logloss: 0.214749
[2200]	valid_0's binary_logloss: 0.214713
[2250]	valid_0's binary_logloss: 0.214689
[2300]	valid_0's binary_logloss: 0.214636
[2350]	valid_0's binary_logloss: 0.214615
[2400]	valid_0's binary_logloss: 0.214563
[2450]	valid_0's binary_logloss: 0.214543
[2500]	valid_0's binary_logloss: 0.214529
[2550]	valid_0's binary_logloss: 0.21452
[2600]	valid_0's binary_logloss: 0.214503
[2650]	valid_0's binary_logloss: 0.214501
[2700]	valid_0's binary_logloss: 0.214509
[2750]	valid_0's binary_logloss: 0.21447
[2800]	valid_0's binary_logloss: 0.214455
[2850]	valid_0's binary_logloss: 0.214417
[2900]	valid_0's binary_logloss: 0.214409
[2950]	valid_0's binary_logloss: 0.214387
[3000]	valid_0's binary_logloss: 0.214401
Early stopping, best iteration is:
[2949]	valid_0's binary_logloss: 0.214386
fit fold=3  858.228[s]

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

 - fold3 - 0.7771

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

Training until validation scores don't improve for 100 rounds
[50]	valid_0's binary_logloss: 0.23284
[100]	valid_0's binary_logloss: 0.229601
[150]	valid_0's binary_logloss: 0.227592
[200]	valid_0's binary_logloss: 0.226135
[250]	valid_0's binary_logloss: 0.225043
[300]	valid_0's binary_logloss: 0.224111
[350]	valid_0's binary_logloss: 0.223228
[400]	valid_0's binary_logloss: 0.222605
[450]	valid_0's binary_logloss: 0.222098
[500]	valid_0's binary_logloss: 0.221461
[550]	valid_0's binary_logloss: 0.220935
[600]	valid_0's binary_logloss: 0.220446
[650]	valid_0's binary_logloss: 0.220098
[700]	valid_0's binary_logloss: 0.219704
[750]	valid_0's binary_logloss: 0.219465
[800]	valid_0's binary_logloss: 0.219198
[850]	valid_0's binary_logloss: 0.218945
[900]	valid_0's binary_logloss: 0.218698
[950]	valid_0's binary_logloss: 0.218456
[1000]	valid_0's binary_logloss: 0.218258
[1050]	valid_0's binary_logloss: 0.218032
[1100]	valid_0's binary_logloss: 0.21786
[1150]	valid_0's binary_logloss: 0.217753
[1200]	valid_0's binary_logloss: 0.21761
[1250]	valid_0's binary_logloss: 0.217492
[1300]	valid_0's binary_logloss: 0.217379
[1350]	valid_0's binary_logloss: 0.217229
[1400]	valid_0's binary_logloss: 0.217141
[1450]	valid_0's binary_logloss: 0.217047
[1500]	valid_0's binary_logloss: 0.216971
[1550]	valid_0's binary_logloss: 0.216892
[1600]	valid_0's binary_logloss: 0.216836
[1650]	valid_0's binary_logloss: 0.216798
[1700]	valid_0's binary_logloss: 0.216688
[1750]	valid_0's binary_logloss: 0.216622
[1800]	valid_0's binary_logloss: 0.21655
[1850]	valid_0's binary_logloss: 0.216496
[1900]	valid_0's binary_logloss: 0.216433
[1950]	valid_0's binary_logloss: 0.216386
[2000]	valid_0's binary_logloss: 0.216311
[2050]	valid_0's binary_logloss: 0.216277
[2100]	valid_0's binary_logloss: 0.216211
[2150]	valid_0's binary_logloss: 0.216169
[2200]	valid_0's binary_logloss: 0.216169
[2250]	valid_0's binary_logloss: 0.216111
[2300]	valid_0's binary_logloss: 0.216093
[2350]	valid_0's binary_logloss: 0.216073
[2400]	valid_0's binary_logloss: 0.216088
Early stopping, best iteration is:
[2339]	valid_0's binary_logloss: 0.216068
fit fold=4  718.789[s]

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

 - fold4 - 0.7756
column=チョコレート 4265.213[s]

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

Training until validation scores don't improve for 100 rounds
[50]	valid_0's binary_logloss: 0.2375
[100]	valid_0's binary_logloss: 0.230673
[150]	valid_0's binary_logloss: 0.225997
[200]	valid_0's binary_logloss: 0.222183
[250]	valid_0's binary_logloss: 0.219096
[300]	valid_0's binary_logloss: 0.216479
[350]	valid_0's binary_logloss: 0.214351
[400]	valid_0's binary_logloss: 0.21237
[450]	valid_0's binary_logloss: 0.210563
[500]	valid_0's binary_logloss: 0.208937
[550]	valid_0's binary_logloss: 0.207491
[600]	valid_0's binary_logloss: 0.206095
[650]	valid_0's binary_logloss: 0.205023
[700]	valid_0's binary_logloss: 0.203995
[750]	valid_0's binary_logloss: 0.203026
[800]	valid_0's binary_logloss: 0.20204
[850]	valid_0's binary_logloss: 0.201242
[900]	valid_0's binary_logloss: 0.200407
[950]	valid_0's binary_logloss: 0.199716
[1000]	valid_0's binary_logloss: 0.199036
[1050]	valid_0's binary_logloss: 0.198426
[1100]	valid_0's binary_logloss: 0.197741
[1150]	valid_0's binary_logloss: 0.197195
[1200]	valid_0's binary_logloss: 0.196645
[1250]	valid_0's binary_logloss: 0.196179
[1300]	valid_0's binary_logloss: 0.195721
[1350]	valid_0's binary_logloss: 0.195223
[1400]	valid_0's binary_logloss: 0.194783
[1450]	valid_0's binary_logloss: 0.194282
[1500]	valid_0's binary_logloss: 0.193931
[1550]	valid_0's binary_logloss: 0.193478
[1600]	valid_0's binary_logloss: 0.192974
[1650]	valid_0's binary_logloss: 0.192584
[1700]	valid_0's binary_logloss: 0.192242
[1750]	valid_0's binary_logloss: 0.192055
[1800]	valid_0's binary_logloss: 0.19176
[1850]	valid_0's binary_logloss: 0.191404
[1900]	valid_0's binary_logloss: 0.191113
[1950]	valid_0's binary_logloss: 0.190936
[2000]	valid_0's binary_logloss: 0.190767
[2050]	valid_0's binary_logloss: 0.19051
[2100]	valid_0's binary_logloss: 0.190274
[2150]	valid_0's binary_logloss: 0.190091
[2200]	valid_0's binary_logloss: 0.189899
[2250]	valid_0's binary_logloss: 0.189633
[2300]	valid_0's binary_logloss: 0.189487
[2350]	valid_0's binary_logloss: 0.189298
[2400]	valid_0's binary_logloss: 0.189098
[2450]	valid_0's binary_logloss: 0.188884
[2500]	valid_0's binary_logloss: 0.188667
[2550]	valid_0's binary_logloss: 0.188462
[2600]	valid_0's binary_logloss: 0.188352
[2650]	valid_0's binary_logloss: 0.188233
[2700]	valid_0's binary_logloss: 0.188114
[2750]	valid_0's binary_logloss: 0.187944
[2800]	valid_0's binary_logloss: 0.187806
[2850]	valid_0's binary_logloss: 0.187659
[2900]	valid_0's binary_logloss: 0.187573
[2950]	valid_0's binary_logloss: 0.18746
[3000]	valid_0's binary_logloss: 0.187343
[3050]	valid_0's binary_logloss: 0.187193
[3100]	valid_0's binary_logloss: 0.187107
[3150]	valid_0's binary_logloss: 0.186962
[3200]	valid_0's binary_logloss: 0.186875
[3250]	valid_0's binary_logloss: 0.186804
[3300]	valid_0's binary_logloss: 0.186722
[3350]	valid_0's binary_logloss: 0.186609
[3400]	valid_0's binary_logloss: 0.186531
[3450]	valid_0's binary_logloss: 0.186445
[3500]	valid_0's binary_logloss: 0.186351
[3550]	valid_0's binary_logloss: 0.186267
[3600]	valid_0's binary_logloss: 0.186206
[3650]	valid_0's binary_logloss: 0.18609
[3700]	valid_0's binary_logloss: 0.186031
[3750]	valid_0's binary_logloss: 0.185983
[3800]	valid_0's binary_logloss: 0.185919
[3850]	valid_0's binary_logloss: 0.185895
[3900]	valid_0's binary_logloss: 0.18583
[3950]	valid_0's binary_logloss: 0.185754
[4000]	valid_0's binary_logloss: 0.185677
[4050]	valid_0's binary_logloss: 0.185635
[4100]	valid_0's binary_logloss: 0.185593
[4150]	valid_0's binary_logloss: 0.185512
[4200]	valid_0's binary_logloss: 0.185466
[4250]	valid_0's binary_logloss: 0.185414
[4300]	valid_0's binary_logloss: 0.185378
[4350]	valid_0's binary_logloss: 0.185354
[4400]	valid_0's binary_logloss: 0.185355
[4450]	valid_0's binary_logloss: 0.185323
[4500]	valid_0's binary_logloss: 0.185293
[4550]	valid_0's binary_logloss: 0.185306
Early stopping, best iteration is:
[4471]	valid_0's binary_logloss: 0.185285
fit fold=0  1262.900[s]

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

 - fold0 - 0.8713

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

Training until validation scores don't improve for 100 rounds
[50]	valid_0's binary_logloss: 0.237829
[100]	valid_0's binary_logloss: 0.230705
[150]	valid_0's binary_logloss: 0.225827
[200]	valid_0's binary_logloss: 0.221882
[250]	valid_0's binary_logloss: 0.218674
[300]	valid_0's binary_logloss: 0.216096
[350]	valid_0's binary_logloss: 0.213902
[400]	valid_0's binary_logloss: 0.211837
[450]	valid_0's binary_logloss: 0.209998
[500]	valid_0's binary_logloss: 0.208333
[550]	valid_0's binary_logloss: 0.207048
[600]	valid_0's binary_logloss: 0.205648
[650]	valid_0's binary_logloss: 0.204619
[700]	valid_0's binary_logloss: 0.203629
[750]	valid_0's binary_logloss: 0.20259
[800]	valid_0's binary_logloss: 0.20167
[850]	valid_0's binary_logloss: 0.200728
[900]	valid_0's binary_logloss: 0.199948
[950]	valid_0's binary_logloss: 0.199189
[1000]	valid_0's binary_logloss: 0.198587
[1050]	valid_0's binary_logloss: 0.198
[1100]	valid_0's binary_logloss: 0.197277
[1150]	valid_0's binary_logloss: 0.196611
[1200]	valid_0's binary_logloss: 0.196159
[1250]	valid_0's binary_logloss: 0.195612
[1300]	valid_0's binary_logloss: 0.195035
[1350]	valid_0's binary_logloss: 0.19472
[1400]	valid_0's binary_logloss: 0.19424
[1450]	valid_0's binary_logloss: 0.193813
[1500]	valid_0's binary_logloss: 0.193477
[1550]	valid_0's binary_logloss: 0.193137
[1600]	valid_0's binary_logloss: 0.192767
[1650]	valid_0's binary_logloss: 0.192407
[1700]	valid_0's binary_logloss: 0.192115
[1750]	valid_0's binary_logloss: 0.191825
[1800]	valid_0's binary_logloss: 0.191475
[1850]	valid_0's binary_logloss: 0.191261
[1900]	valid_0's binary_logloss: 0.190997
[1950]	valid_0's binary_logloss: 0.190749
[2000]	valid_0's binary_logloss: 0.190589
[2050]	valid_0's binary_logloss: 0.190281
[2100]	valid_0's binary_logloss: 0.190108
[2150]	valid_0's binary_logloss: 0.189887
[2200]	valid_0's binary_logloss: 0.189661
[2250]	valid_0's binary_logloss: 0.189497
[2300]	valid_0's binary_logloss: 0.189376
[2350]	valid_0's binary_logloss: 0.189281
[2400]	valid_0's binary_logloss: 0.189127
[2450]	valid_0's binary_logloss: 0.188921
[2500]	valid_0's binary_logloss: 0.188751
[2550]	valid_0's binary_logloss: 0.188612
[2600]	valid_0's binary_logloss: 0.188458
[2650]	valid_0's binary_logloss: 0.18833
[2700]	valid_0's binary_logloss: 0.188217
[2750]	valid_0's binary_logloss: 0.188165
[2800]	valid_0's binary_logloss: 0.188016
[2850]	valid_0's binary_logloss: 0.187847
[2900]	valid_0's binary_logloss: 0.187733
[2950]	valid_0's binary_logloss: 0.187664
[3000]	valid_0's binary_logloss: 0.187561
[3050]	valid_0's binary_logloss: 0.187438
[3100]	valid_0's binary_logloss: 0.187298
[3150]	valid_0's binary_logloss: 0.187217
[3200]	valid_0's binary_logloss: 0.187146
[3250]	valid_0's binary_logloss: 0.187091
[3300]	valid_0's binary_logloss: 0.186998
[3350]	valid_0's binary_logloss: 0.186958
[3400]	valid_0's binary_logloss: 0.186901
[3450]	valid_0's binary_logloss: 0.186813
[3500]	valid_0's binary_logloss: 0.186759
[3550]	valid_0's binary_logloss: 0.18669
[3600]	valid_0's binary_logloss: 0.186659
[3650]	valid_0's binary_logloss: 0.186625
[3700]	valid_0's binary_logloss: 0.186545
[3750]	valid_0's binary_logloss: 0.186497
[3800]	valid_0's binary_logloss: 0.186434
[3850]	valid_0's binary_logloss: 0.186424
[3900]	valid_0's binary_logloss: 0.186393
[3950]	valid_0's binary_logloss: 0.186355
[4000]	valid_0's binary_logloss: 0.186335
[4050]	valid_0's binary_logloss: 0.186293
[4100]	valid_0's binary_logloss: 0.186261
[4150]	valid_0's binary_logloss: 0.186191
[4200]	valid_0's binary_logloss: 0.186172
[4250]	valid_0's binary_logloss: 0.186167
[4300]	valid_0's binary_logloss: 0.186128
[4350]	valid_0's binary_logloss: 0.186122
[4400]	valid_0's binary_logloss: 0.186094
[4450]	valid_0's binary_logloss: 0.186079
[4500]	valid_0's binary_logloss: 0.186048
[4550]	valid_0's binary_logloss: 0.186004
[4600]	valid_0's binary_logloss: 0.185967
[4650]	valid_0's binary_logloss: 0.185932
[4700]	valid_0's binary_logloss: 0.185888
[4750]	valid_0's binary_logloss: 0.185841
[4800]	valid_0's binary_logloss: 0.185807
[4850]	valid_0's binary_logloss: 0.18578
[4900]	valid_0's binary_logloss: 0.185759
[4950]	valid_0's binary_logloss: 0.18574
[5000]	valid_0's binary_logloss: 0.185754
Early stopping, best iteration is:
[4947]	valid_0's binary_logloss: 0.18573
fit fold=1  1398.378[s]

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

 - fold1 - 0.8710

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

Training until validation scores don't improve for 100 rounds
[50]	valid_0's binary_logloss: 0.23758
[100]	valid_0's binary_logloss: 0.230741
[150]	valid_0's binary_logloss: 0.226032
[200]	valid_0's binary_logloss: 0.222431
[250]	valid_0's binary_logloss: 0.219359
[300]	valid_0's binary_logloss: 0.216626
[350]	valid_0's binary_logloss: 0.214395
[400]	valid_0's binary_logloss: 0.21234
[450]	valid_0's binary_logloss: 0.210455
[500]	valid_0's binary_logloss: 0.208947
[550]	valid_0's binary_logloss: 0.207554
[600]	valid_0's binary_logloss: 0.206318
[650]	valid_0's binary_logloss: 0.205271
[700]	valid_0's binary_logloss: 0.20426
[750]	valid_0's binary_logloss: 0.203094
[800]	valid_0's binary_logloss: 0.202208
[850]	valid_0's binary_logloss: 0.201408
[900]	valid_0's binary_logloss: 0.200619
[950]	valid_0's binary_logloss: 0.199851
[1000]	valid_0's binary_logloss: 0.199066
[1050]	valid_0's binary_logloss: 0.198294
[1100]	valid_0's binary_logloss: 0.197641
[1150]	valid_0's binary_logloss: 0.197112
[1200]	valid_0's binary_logloss: 0.196496
[1250]	valid_0's binary_logloss: 0.196052
[1300]	valid_0's binary_logloss: 0.195485
[1350]	valid_0's binary_logloss: 0.195051
[1400]	valid_0's binary_logloss: 0.194684
[1450]	valid_0's binary_logloss: 0.194322
[1500]	valid_0's binary_logloss: 0.193993
[1550]	valid_0's binary_logloss: 0.19365
[1600]	valid_0's binary_logloss: 0.193314
[1650]	valid_0's binary_logloss: 0.192984
[1700]	valid_0's binary_logloss: 0.192703
[1750]	valid_0's binary_logloss: 0.192381
[1800]	valid_0's binary_logloss: 0.192137
[1850]	valid_0's binary_logloss: 0.191844
[1900]	valid_0's binary_logloss: 0.191527
[1950]	valid_0's binary_logloss: 0.191296
[2000]	valid_0's binary_logloss: 0.191072
[2050]	valid_0's binary_logloss: 0.190896
[2100]	valid_0's binary_logloss: 0.190637
[2150]	valid_0's binary_logloss: 0.190459
[2200]	valid_0's binary_logloss: 0.19024
[2250]	valid_0's binary_logloss: 0.190047
[2300]	valid_0's binary_logloss: 0.189906
[2350]	valid_0's binary_logloss: 0.189721
[2400]	valid_0's binary_logloss: 0.189548
[2450]	valid_0's binary_logloss: 0.189407
[2500]	valid_0's binary_logloss: 0.189263
[2550]	valid_0's binary_logloss: 0.18912
[2600]	valid_0's binary_logloss: 0.18898
[2650]	valid_0's binary_logloss: 0.188822
[2700]	valid_0's binary_logloss: 0.188774
[2750]	valid_0's binary_logloss: 0.188668
[2800]	valid_0's binary_logloss: 0.188581
[2850]	valid_0's binary_logloss: 0.18849
[2900]	valid_0's binary_logloss: 0.188378
[2950]	valid_0's binary_logloss: 0.188305
[3000]	valid_0's binary_logloss: 0.188207
[3050]	valid_0's binary_logloss: 0.18815
[3100]	valid_0's binary_logloss: 0.188046
[3150]	valid_0's binary_logloss: 0.187939
[3200]	valid_0's binary_logloss: 0.187838
[3250]	valid_0's binary_logloss: 0.187763
[3300]	valid_0's binary_logloss: 0.187672
[3350]	valid_0's binary_logloss: 0.187581
[3400]	valid_0's binary_logloss: 0.187455
[3450]	valid_0's binary_logloss: 0.187373
[3500]	valid_0's binary_logloss: 0.187295
[3550]	valid_0's binary_logloss: 0.187235
[3600]	valid_0's binary_logloss: 0.187178
[3650]	valid_0's binary_logloss: 0.187189
[3700]	valid_0's binary_logloss: 0.187141
[3750]	valid_0's binary_logloss: 0.187066
[3800]	valid_0's binary_logloss: 0.187019
[3850]	valid_0's binary_logloss: 0.187002
[3900]	valid_0's binary_logloss: 0.186964
[3950]	valid_0's binary_logloss: 0.186924
[4000]	valid_0's binary_logloss: 0.18688
[4050]	valid_0's binary_logloss: 0.186814
[4100]	valid_0's binary_logloss: 0.186762
[4150]	valid_0's binary_logloss: 0.186721
[4200]	valid_0's binary_logloss: 0.186668
[4250]	valid_0's binary_logloss: 0.186641
[4300]	valid_0's binary_logloss: 0.186605
[4350]	valid_0's binary_logloss: 0.186591
[4400]	valid_0's binary_logloss: 0.186563
[4450]	valid_0's binary_logloss: 0.18654
[4500]	valid_0's binary_logloss: 0.186509
[4550]	valid_0's binary_logloss: 0.186451
[4600]	valid_0's binary_logloss: 0.186443
[4650]	valid_0's binary_logloss: 0.186425
[4700]	valid_0's binary_logloss: 0.18637
[4750]	valid_0's binary_logloss: 0.186364
[4800]	valid_0's binary_logloss: 0.186331
[4850]	valid_0's binary_logloss: 0.186331
[4900]	valid_0's binary_logloss: 0.186331
Early stopping, best iteration is:
[4804]	valid_0's binary_logloss: 0.186319
fit fold=2  1345.212[s]

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

 - fold2 - 0.8689

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

Training until validation scores don't improve for 100 rounds
[50]	valid_0's binary_logloss: 0.237685
[100]	valid_0's binary_logloss: 0.23066
[150]	valid_0's binary_logloss: 0.226174
[200]	valid_0's binary_logloss: 0.222337
[250]	valid_0's binary_logloss: 0.219417
[300]	valid_0's binary_logloss: 0.216774
[350]	valid_0's binary_logloss: 0.214466
[400]	valid_0's binary_logloss: 0.212438
[450]	valid_0's binary_logloss: 0.210667
[500]	valid_0's binary_logloss: 0.209102
[550]	valid_0's binary_logloss: 0.207575
[600]	valid_0's binary_logloss: 0.206397
[650]	valid_0's binary_logloss: 0.205326
[700]	valid_0's binary_logloss: 0.204127
[750]	valid_0's binary_logloss: 0.203239
[800]	valid_0's binary_logloss: 0.202362
[850]	valid_0's binary_logloss: 0.201558
[900]	valid_0's binary_logloss: 0.200741
[950]	valid_0's binary_logloss: 0.199905
[1000]	valid_0's binary_logloss: 0.199211
[1050]	valid_0's binary_logloss: 0.198488
[1100]	valid_0's binary_logloss: 0.197859
[1150]	valid_0's binary_logloss: 0.197263
[1200]	valid_0's binary_logloss: 0.196708
[1250]	valid_0's binary_logloss: 0.196184
[1300]	valid_0's binary_logloss: 0.195784
[1350]	valid_0's binary_logloss: 0.19535
[1400]	valid_0's binary_logloss: 0.194868
[1450]	valid_0's binary_logloss: 0.194479
[1500]	valid_0's binary_logloss: 0.194125
[1550]	valid_0's binary_logloss: 0.193744
[1600]	valid_0's binary_logloss: 0.193374
[1650]	valid_0's binary_logloss: 0.192992
[1700]	valid_0's binary_logloss: 0.192723
[1750]	valid_0's binary_logloss: 0.192377
[1800]	valid_0's binary_logloss: 0.192075
[1850]	valid_0's binary_logloss: 0.191834
[1900]	valid_0's binary_logloss: 0.191504
[1950]	valid_0's binary_logloss: 0.191185
[2000]	valid_0's binary_logloss: 0.190955
[2050]	valid_0's binary_logloss: 0.190628
[2100]	valid_0's binary_logloss: 0.190381
[2150]	valid_0's binary_logloss: 0.190115
[2200]	valid_0's binary_logloss: 0.189876
[2250]	valid_0's binary_logloss: 0.18966
[2300]	valid_0's binary_logloss: 0.189516
[2350]	valid_0's binary_logloss: 0.189381
[2400]	valid_0's binary_logloss: 0.189218
[2450]	valid_0's binary_logloss: 0.189046
[2500]	valid_0's binary_logloss: 0.188922
[2550]	valid_0's binary_logloss: 0.188844
[2600]	valid_0's binary_logloss: 0.188649
[2650]	valid_0's binary_logloss: 0.188402
[2700]	valid_0's binary_logloss: 0.188292
[2750]	valid_0's binary_logloss: 0.188192
[2800]	valid_0's binary_logloss: 0.188048
[2850]	valid_0's binary_logloss: 0.187918
[2900]	valid_0's binary_logloss: 0.187827
[2950]	valid_0's binary_logloss: 0.187763
[3000]	valid_0's binary_logloss: 0.187669
[3050]	valid_0's binary_logloss: 0.187533
[3100]	valid_0's binary_logloss: 0.187428
[3150]	valid_0's binary_logloss: 0.187304
[3200]	valid_0's binary_logloss: 0.187249
[3250]	valid_0's binary_logloss: 0.187202
[3300]	valid_0's binary_logloss: 0.187149
[3350]	valid_0's binary_logloss: 0.187082
[3400]	valid_0's binary_logloss: 0.186997
[3450]	valid_0's binary_logloss: 0.186954
[3500]	valid_0's binary_logloss: 0.186885
[3550]	valid_0's binary_logloss: 0.186836
[3600]	valid_0's binary_logloss: 0.186772
[3650]	valid_0's binary_logloss: 0.18673
[3700]	valid_0's binary_logloss: 0.186698
[3750]	valid_0's binary_logloss: 0.186625
[3800]	valid_0's binary_logloss: 0.186583
[3850]	valid_0's binary_logloss: 0.186551
[3900]	valid_0's binary_logloss: 0.18651
[3950]	valid_0's binary_logloss: 0.186425
[4000]	valid_0's binary_logloss: 0.186376
[4050]	valid_0's binary_logloss: 0.186361
[4100]	valid_0's binary_logloss: 0.186292
[4150]	valid_0's binary_logloss: 0.186248
[4200]	valid_0's binary_logloss: 0.186221
[4250]	valid_0's binary_logloss: 0.186172
[4300]	valid_0's binary_logloss: 0.186174
[4350]	valid_0's binary_logloss: 0.186167
[4400]	valid_0's binary_logloss: 0.186174
[4450]	valid_0's binary_logloss: 0.186155
[4500]	valid_0's binary_logloss: 0.186115
[4550]	valid_0's binary_logloss: 0.186127
[4600]	valid_0's binary_logloss: 0.186111
[4650]	valid_0's binary_logloss: 0.186082
[4700]	valid_0's binary_logloss: 0.186053
[4750]	valid_0's binary_logloss: 0.185989
[4800]	valid_0's binary_logloss: 0.185937
[4850]	valid_0's binary_logloss: 0.185877
[4900]	valid_0's binary_logloss: 0.185859
[4950]	valid_0's binary_logloss: 0.185796
[5000]	valid_0's binary_logloss: 0.185808
[5050]	valid_0's binary_logloss: 0.185803
Early stopping, best iteration is:
[4952]	valid_0's binary_logloss: 0.18578
fit fold=3  1383.687[s]

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

 - fold3 - 0.8698

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

Training until validation scores don't improve for 100 rounds
[50]	valid_0's binary_logloss: 0.239484
[100]	valid_0's binary_logloss: 0.232434
[150]	valid_0's binary_logloss: 0.227722
[200]	valid_0's binary_logloss: 0.223949
[250]	valid_0's binary_logloss: 0.220893
[300]	valid_0's binary_logloss: 0.218332
[350]	valid_0's binary_logloss: 0.215989
[400]	valid_0's binary_logloss: 0.214078
[450]	valid_0's binary_logloss: 0.212392
[500]	valid_0's binary_logloss: 0.210824
[550]	valid_0's binary_logloss: 0.209409
[600]	valid_0's binary_logloss: 0.208201
[650]	valid_0's binary_logloss: 0.20691
[700]	valid_0's binary_logloss: 0.205999
[750]	valid_0's binary_logloss: 0.205089
[800]	valid_0's binary_logloss: 0.204
[850]	valid_0's binary_logloss: 0.203295
[900]	valid_0's binary_logloss: 0.202478
[950]	valid_0's binary_logloss: 0.201624
[1000]	valid_0's binary_logloss: 0.200838
[1050]	valid_0's binary_logloss: 0.200329
[1100]	valid_0's binary_logloss: 0.19966
[1150]	valid_0's binary_logloss: 0.199037
[1200]	valid_0's binary_logloss: 0.198428
[1250]	valid_0's binary_logloss: 0.197902
[1300]	valid_0's binary_logloss: 0.197438
[1350]	valid_0's binary_logloss: 0.196912
[1400]	valid_0's binary_logloss: 0.196502
[1450]	valid_0's binary_logloss: 0.196137
[1500]	valid_0's binary_logloss: 0.195784
[1550]	valid_0's binary_logloss: 0.195497
[1600]	valid_0's binary_logloss: 0.195198
[1650]	valid_0's binary_logloss: 0.194814
[1700]	valid_0's binary_logloss: 0.194444
[1750]	valid_0's binary_logloss: 0.194057
[1800]	valid_0's binary_logloss: 0.193873
[1850]	valid_0's binary_logloss: 0.193546
[1900]	valid_0's binary_logloss: 0.193245
[1950]	valid_0's binary_logloss: 0.192999
[2000]	valid_0's binary_logloss: 0.192742
[2050]	valid_0's binary_logloss: 0.19255
[2100]	valid_0's binary_logloss: 0.192287
[2150]	valid_0's binary_logloss: 0.192133
[2200]	valid_0's binary_logloss: 0.19191
[2250]	valid_0's binary_logloss: 0.191646
[2300]	valid_0's binary_logloss: 0.191508
[2350]	valid_0's binary_logloss: 0.191289
[2400]	valid_0's binary_logloss: 0.191087
[2450]	valid_0's binary_logloss: 0.190897
[2500]	valid_0's binary_logloss: 0.190731
[2550]	valid_0's binary_logloss: 0.1906
[2600]	valid_0's binary_logloss: 0.19049
[2650]	valid_0's binary_logloss: 0.190328
[2700]	valid_0's binary_logloss: 0.19019
[2750]	valid_0's binary_logloss: 0.190046
[2800]	valid_0's binary_logloss: 0.189906
[2850]	valid_0's binary_logloss: 0.189758
[2900]	valid_0's binary_logloss: 0.189664
[2950]	valid_0's binary_logloss: 0.189563
[3000]	valid_0's binary_logloss: 0.189456
[3050]	valid_0's binary_logloss: 0.189372
[3100]	valid_0's binary_logloss: 0.189265
[3150]	valid_0's binary_logloss: 0.189128
[3200]	valid_0's binary_logloss: 0.189018
[3250]	valid_0's binary_logloss: 0.188968
[3300]	valid_0's binary_logloss: 0.188876
[3350]	valid_0's binary_logloss: 0.188765
[3400]	valid_0's binary_logloss: 0.188698
[3450]	valid_0's binary_logloss: 0.188628
[3500]	valid_0's binary_logloss: 0.188601
[3550]	valid_0's binary_logloss: 0.188534
[3600]	valid_0's binary_logloss: 0.188487
[3650]	valid_0's binary_logloss: 0.188451
[3700]	valid_0's binary_logloss: 0.188352
[3750]	valid_0's binary_logloss: 0.188265
[3800]	valid_0's binary_logloss: 0.188244
[3850]	valid_0's binary_logloss: 0.188168
[3900]	valid_0's binary_logloss: 0.188072
[3950]	valid_0's binary_logloss: 0.188017
[4000]	valid_0's binary_logloss: 0.187958
[4050]	valid_0's binary_logloss: 0.187915
[4100]	valid_0's binary_logloss: 0.187843
[4150]	valid_0's binary_logloss: 0.187786
[4200]	valid_0's binary_logloss: 0.187733
[4250]	valid_0's binary_logloss: 0.187688
[4300]	valid_0's binary_logloss: 0.187621
[4350]	valid_0's binary_logloss: 0.187575
[4400]	valid_0's binary_logloss: 0.187547
[4450]	valid_0's binary_logloss: 0.187527
[4500]	valid_0's binary_logloss: 0.187491
[4550]	valid_0's binary_logloss: 0.187448
[4600]	valid_0's binary_logloss: 0.187395
[4650]	valid_0's binary_logloss: 0.1874
[4700]	valid_0's binary_logloss: 0.187394
[4750]	valid_0's binary_logloss: 0.18737
[4800]	valid_0's binary_logloss: 0.187329
[4850]	valid_0's binary_logloss: 0.187331
[4900]	valid_0's binary_logloss: 0.187298
[4950]	valid_0's binary_logloss: 0.187264
[5000]	valid_0's binary_logloss: 0.187249
[5050]	valid_0's binary_logloss: 0.187246
Early stopping, best iteration is:
[4983]	valid_0's binary_logloss: 0.187236
fit fold=4  1392.481[s]

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

 - fold4 - 0.8700
column=ビール 7630.788[s]

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

Training until validation scores don't improve for 100 rounds
[50]	valid_0's binary_logloss: 0.122821
[100]	valid_0's binary_logloss: 0.121991
[150]	valid_0's binary_logloss: 0.121709
[200]	valid_0's binary_logloss: 0.121499
[250]	valid_0's binary_logloss: 0.121316
[300]	valid_0's binary_logloss: 0.121136
[350]	valid_0's binary_logloss: 0.121015
[400]	valid_0's binary_logloss: 0.120946
[450]	valid_0's binary_logloss: 0.120884
[500]	valid_0's binary_logloss: 0.120813
[550]	valid_0's binary_logloss: 0.120761
[600]	valid_0's binary_logloss: 0.120714
[650]	valid_0's binary_logloss: 0.120679
[700]	valid_0's binary_logloss: 0.120693
[750]	valid_0's binary_logloss: 0.120628
[800]	valid_0's binary_logloss: 0.120592
[850]	valid_0's binary_logloss: 0.120601
Early stopping, best iteration is:
[795]	valid_0's binary_logloss: 0.120588
fit fold=0  273.773[s]

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

 - fold0 - 0.7186

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

Training until validation scores don't improve for 100 rounds
[50]	valid_0's binary_logloss: 0.121223
[100]	valid_0's binary_logloss: 0.120486
[150]	valid_0's binary_logloss: 0.120209
[200]	valid_0's binary_logloss: 0.119999
[250]	valid_0's binary_logloss: 0.119849
[300]	valid_0's binary_logloss: 0.119736
[350]	valid_0's binary_logloss: 0.119645
[400]	valid_0's binary_logloss: 0.119551
[450]	valid_0's binary_logloss: 0.119488
[500]	valid_0's binary_logloss: 0.119461
[550]	valid_0's binary_logloss: 0.119414
[600]	valid_0's binary_logloss: 0.1194
[650]	valid_0's binary_logloss: 0.119398
[700]	valid_0's binary_logloss: 0.119364
[750]	valid_0's binary_logloss: 0.119355
[800]	valid_0's binary_logloss: 0.119339
[850]	valid_0's binary_logloss: 0.119334
[900]	valid_0's binary_logloss: 0.119327
[950]	valid_0's binary_logloss: 0.119297
[1000]	valid_0's binary_logloss: 0.119271
[1050]	valid_0's binary_logloss: 0.11928
[1100]	valid_0's binary_logloss: 0.119304
Early stopping, best iteration is:
[1001]	valid_0's binary_logloss: 0.119269
fit fold=1  331.123[s]

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

 - fold1 - 0.7139

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

Training until validation scores don't improve for 100 rounds
[50]	valid_0's binary_logloss: 0.122211
[100]	valid_0's binary_logloss: 0.12145
[150]	valid_0's binary_logloss: 0.121146
[200]	valid_0's binary_logloss: 0.120981
[250]	valid_0's binary_logloss: 0.120862
[300]	valid_0's binary_logloss: 0.120709
[350]	valid_0's binary_logloss: 0.120607
[400]	valid_0's binary_logloss: 0.120552
[450]	valid_0's binary_logloss: 0.120528
[500]	valid_0's binary_logloss: 0.120476
[550]	valid_0's binary_logloss: 0.120438
[600]	valid_0's binary_logloss: 0.120398
[650]	valid_0's binary_logloss: 0.120374
[700]	valid_0's binary_logloss: 0.120369
[750]	valid_0's binary_logloss: 0.120351
[800]	valid_0's binary_logloss: 0.120367
[850]	valid_0's binary_logloss: 0.12036
Early stopping, best iteration is:
[755]	valid_0's binary_logloss: 0.120341
fit fold=2  268.906[s]

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

 - fold2 - 0.7143

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

Training until validation scores don't improve for 100 rounds
[50]	valid_0's binary_logloss: 0.121103
[100]	valid_0's binary_logloss: 0.120331
[150]	valid_0's binary_logloss: 0.120034
[200]	valid_0's binary_logloss: 0.119847
[250]	valid_0's binary_logloss: 0.119739
[300]	valid_0's binary_logloss: 0.119627
[350]	valid_0's binary_logloss: 0.119554
[400]	valid_0's binary_logloss: 0.119479
[450]	valid_0's binary_logloss: 0.119405
[500]	valid_0's binary_logloss: 0.119358
[550]	valid_0's binary_logloss: 0.119305
[600]	valid_0's binary_logloss: 0.119257
[650]	valid_0's binary_logloss: 0.119223
[700]	valid_0's binary_logloss: 0.119209
[750]	valid_0's binary_logloss: 0.119173
[800]	valid_0's binary_logloss: 0.119174
[850]	valid_0's binary_logloss: 0.119171
[900]	valid_0's binary_logloss: 0.119178
Early stopping, best iteration is:
[842]	valid_0's binary_logloss: 0.119158
fit fold=3  291.958[s]

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

 - fold3 - 0.7151

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

Training until validation scores don't improve for 100 rounds
[50]	valid_0's binary_logloss: 0.121004
[100]	valid_0's binary_logloss: 0.120236
[150]	valid_0's binary_logloss: 0.119855
[200]	valid_0's binary_logloss: 0.11963
[250]	valid_0's binary_logloss: 0.119468
[300]	valid_0's binary_logloss: 0.119367
[350]	valid_0's binary_logloss: 0.119257
[400]	valid_0's binary_logloss: 0.119148
[450]	valid_0's binary_logloss: 0.119109
[500]	valid_0's binary_logloss: 0.119041
[550]	valid_0's binary_logloss: 0.119009
[600]	valid_0's binary_logloss: 0.118948
[650]	valid_0's binary_logloss: 0.118919
[700]	valid_0's binary_logloss: 0.118882
[750]	valid_0's binary_logloss: 0.11888
[800]	valid_0's binary_logloss: 0.118874
[850]	valid_0's binary_logloss: 0.118869
[900]	valid_0's binary_logloss: 0.118862
[950]	valid_0's binary_logloss: 0.118862
Early stopping, best iteration is:
[880]	valid_0's binary_logloss: 0.118851
fit fold=4  299.858[s]

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

 - fold4 - 0.7176
column=ヘアケア 1620.996[s]

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

Training until validation scores don't improve for 100 rounds
[50]	valid_0's binary_logloss: 0.0936504
[100]	valid_0's binary_logloss: 0.092749
[150]	valid_0's binary_logloss: 0.0924697
[200]	valid_0's binary_logloss: 0.0922467
[250]	valid_0's binary_logloss: 0.0919911
[300]	valid_0's binary_logloss: 0.0918384
[350]	valid_0's binary_logloss: 0.0916885
[400]	valid_0's binary_logloss: 0.0916246
[450]	valid_0's binary_logloss: 0.0915257
[500]	valid_0's binary_logloss: 0.0914466
[550]	valid_0's binary_logloss: 0.0914372
[600]	valid_0's binary_logloss: 0.0913605
[650]	valid_0's binary_logloss: 0.0912689
[700]	valid_0's binary_logloss: 0.0912314
[750]	valid_0's binary_logloss: 0.0912157
[800]	valid_0's binary_logloss: 0.0911965
[850]	valid_0's binary_logloss: 0.0911541
[900]	valid_0's binary_logloss: 0.0911216
[950]	valid_0's binary_logloss: 0.0911125
[1000]	valid_0's binary_logloss: 0.0910864
[1050]	valid_0's binary_logloss: 0.0910615
[1100]	valid_0's binary_logloss: 0.0910348
[1150]	valid_0's binary_logloss: 0.0910427
[1200]	valid_0's binary_logloss: 0.0910421
Early stopping, best iteration is:
[1106]	valid_0's binary_logloss: 0.0910248
fit fold=0  343.271[s]

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

 - fold0 - 0.7348

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

Training until validation scores don't improve for 100 rounds
[50]	valid_0's binary_logloss: 0.0935121
[100]	valid_0's binary_logloss: 0.0926888
[150]	valid_0's binary_logloss: 0.0921995
[200]	valid_0's binary_logloss: 0.0919463
[250]	valid_0's binary_logloss: 0.0917438
[300]	valid_0's binary_logloss: 0.0915739
[350]	valid_0's binary_logloss: 0.0915201
[400]	valid_0's binary_logloss: 0.0914203
[450]	valid_0's binary_logloss: 0.0913157
[500]	valid_0's binary_logloss: 0.0912527
[550]	valid_0's binary_logloss: 0.0911558
[600]	valid_0's binary_logloss: 0.0910509
[650]	valid_0's binary_logloss: 0.0909727
[700]	valid_0's binary_logloss: 0.0909283
[750]	valid_0's binary_logloss: 0.0908816
[800]	valid_0's binary_logloss: 0.0908662
[850]	valid_0's binary_logloss: 0.0908415
[900]	valid_0's binary_logloss: 0.0908713
Early stopping, best iteration is:
[845]	valid_0's binary_logloss: 0.0908381
fit fold=1  278.219[s]

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

 - fold1 - 0.7346

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

Training until validation scores don't improve for 100 rounds
[50]	valid_0's binary_logloss: 0.0934242
[100]	valid_0's binary_logloss: 0.092498
[150]	valid_0's binary_logloss: 0.0921442
[200]	valid_0's binary_logloss: 0.0918797
[250]	valid_0's binary_logloss: 0.0916186
[300]	valid_0's binary_logloss: 0.0914813
[350]	valid_0's binary_logloss: 0.0913315
[400]	valid_0's binary_logloss: 0.0912094
[450]	valid_0's binary_logloss: 0.0910667
[500]	valid_0's binary_logloss: 0.090984
[550]	valid_0's binary_logloss: 0.0909116
[600]	valid_0's binary_logloss: 0.0907882
[650]	valid_0's binary_logloss: 0.0907035
[700]	valid_0's binary_logloss: 0.0906407
[750]	valid_0's binary_logloss: 0.0906056
[800]	valid_0's binary_logloss: 0.0905665
[850]	valid_0's binary_logloss: 0.0905352
[900]	valid_0's binary_logloss: 0.0904853
[950]	valid_0's binary_logloss: 0.0904683
[1000]	valid_0's binary_logloss: 0.0904638
[1050]	valid_0's binary_logloss: 0.0904018
[1100]	valid_0's binary_logloss: 0.0903771
[1150]	valid_0's binary_logloss: 0.0903706
[1200]	valid_0's binary_logloss: 0.0903575
[1250]	valid_0's binary_logloss: 0.090314
[1300]	valid_0's binary_logloss: 0.0903317
[1350]	valid_0's binary_logloss: 0.0903569
Early stopping, best iteration is:
[1259]	valid_0's binary_logloss: 0.0903121
fit fold=2  448.926[s]

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

 - fold2 - 0.7413

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

Training until validation scores don't improve for 100 rounds
[50]	valid_0's binary_logloss: 0.0916268
[100]	valid_0's binary_logloss: 0.0907466
[150]	valid_0's binary_logloss: 0.0902995
[200]	valid_0's binary_logloss: 0.0900386
[250]	valid_0's binary_logloss: 0.0898508
[300]	valid_0's binary_logloss: 0.0897155
[350]	valid_0's binary_logloss: 0.0895788
[400]	valid_0's binary_logloss: 0.0895117
[450]	valid_0's binary_logloss: 0.0894214
[500]	valid_0's binary_logloss: 0.0893641
[550]	valid_0's binary_logloss: 0.0892894
[600]	valid_0's binary_logloss: 0.0891963
[650]	valid_0's binary_logloss: 0.0891596
[700]	valid_0's binary_logloss: 0.089097
[750]	valid_0's binary_logloss: 0.0889993
[800]	valid_0's binary_logloss: 0.0889847
[850]	valid_0's binary_logloss: 0.0889245
[900]	valid_0's binary_logloss: 0.0889241
[950]	valid_0's binary_logloss: 0.0888827
[1000]	valid_0's binary_logloss: 0.0888443
[1050]	valid_0's binary_logloss: 0.0888132
[1100]	valid_0's binary_logloss: 0.0888147
[1150]	valid_0's binary_logloss: 0.0888095
Early stopping, best iteration is:
[1080]	valid_0's binary_logloss: 0.0887922
fit fold=3  334.852[s]

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

 - fold3 - 0.7366

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

Training until validation scores don't improve for 100 rounds
[50]	valid_0's binary_logloss: 0.0926765
[100]	valid_0's binary_logloss: 0.0918234
[150]	valid_0's binary_logloss: 0.0914118
[200]	valid_0's binary_logloss: 0.0911633

In [ ]:
oof_df = pd.DataFrame()

for col_i, (oof, _) in zip(TARGET_COLUMNS, results):
    oof_df[col_i] = oof

In [ ]:
roc_auc_score(target_df.values, oof_df.values)

In [ ]:
train_feat_df.head()

In [ ]:
def visualize_importance(models, feat_train_df):
    """lightGBM の model 配列の feature importance を plot する
    CVごとのブレを boxen plot として表現します.

    args:
        models:
            List of lightGBM models
        feat_train_df:
            学習時に使った DataFrame
    """
    feature_importance_df = pd.DataFrame()
    for i, model in enumerate(models):
        _df = pd.DataFrame()
        _df["feature_importance"] = model.feature_importances_
        _df["column"] = feat_train_df.columns
        _df["fold"] = i + 1
        feature_importance_df = pd.concat([feature_importance_df, _df],
                                          axis=0, ignore_index=True)

    order = feature_importance_df.groupby("column")\
        .sum()[["feature_importance"]]\
        .sort_values("feature_importance", ascending=False).index[:50]

    fig, ax = plt.subplots(figsize=(8, max(6, len(order) * .25)))
    sns.boxenplot(data=feature_importance_df,
                  x="feature_importance",
                  y="column",
                  order=order,
                  ax=ax,
                  palette="viridis",
                  orient="h")
    ax.tick_params(axis="x", rotation=90)
    ax.set_title("Importance")
    ax.grid()
    fig.tight_layout()
    return fig, ax

In [ ]:
for col_i, (oof, models) in zip(TARGET_COLUMNS, results):
    fig, ax = visualize_importance(models, train_feat_df)
    ax.set_title(col_i)

In [ ]:
submission_df = pd.DataFrame()

for col_i, (oof, models) in zip(TARGET_COLUMNS, results):
    predicts = [model.predict_proba(test_feat_df.values)[:, 1] for model in models]
    predict_i = np.array(predicts).mean(axis=0)

    submission_df[col_i] = predict_i

In [ ]:
for c in TARGET_COLUMNS:
    fig, ax = plt.subplots(figsize=(8, 5))

    sns.histplot(oof_df[c], ax=ax, label="OOF", kde=True)
    sns.histplot(submission_df[c], ax=ax, label="Test", kde=True)

    ax.set_xlabel("予測値", fontproperties=font_prop)  # x軸ラベルの文字化けを防ぐ
    ax.set_ylabel("Count", fontproperties=font_prop)  # y軸ラベルも設定
    ax.set_title(c, fontproperties=font_prop)  # 日本語タイトル対応
    ax.legend()
    ax.grid()

    plt.show()

In [ ]:
import os

In [ ]:
OUTPUT_DIR = "/content/drive/MyDrive/atma/tutorial_1"

os.makedirs(OUTPUT_DIR, exist_ok=True)

In [ ]:
submission_df.to_csv(os.path.join(OUTPUT_DIR, "#7__submission.csv"), index=False)

In [51]:
rm -rf ~/.cache/matplotlib